name: Publish Portfolio

on:
  workflow_dispatch:

jobs:
  buile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true

      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        with:
          source_folder: "dist/*"
          destination_repo: "TK-moon/portfolio"
          destination_folder: "/"
